#!/usr/bin/env bash 
if [ -z “${BASH:-}” ]; then
   exec bash “$0” “$@”
fi

sh "$(dirname "$0")/_/husky.sh"
## section for git-secrets
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi
# Initialise git-secrets configuration
git-secrets --register-aws > /dev/null
git-secrets --register-gcp > /dev/null
git-secrets --add '(ghu|ghs|ghp|gho|ghr)_[0-9a-zA-Z]{36}' > /dev/null
git secrets --add 'password\s*=\s*.+' > /dev/null

echo "Running git-secrets..."
# Scans the commit message.
git-secrets  --pre_commit_hook -- "$@"

